In [1]:
# Import dependencies
import pandas as pd
from pathlib import Path

# Declare filepath variables for CSVs
census_data_path = "Resources/ACSST1Y2022.S1901-2023-11-29T020523.csv"
cw_data_path = "Resources/CWData.csv"

# Create dataframes from CSVs
census_data = pd.read_csv(census_data_path)
cw_data = pd.read_csv(cw_data_path)

# Census Data

In [2]:
# Check work
census_data.head()

,Label (Grouping),Texas!!Households!!Estimate,Texas!!Families!!Estimate,Texas!!Married-couple families!!Estimate,Texas!!Nonfamily households!!Estimate,"Angelina County, Texas!!Households!!Estimate","Angelina County, Texas!!Families!!Estimate","Angelina County, Texas!!Married-couple families!!Estimate","Angelina County, Texas!!Nonfamily households!!Estimate","Bastrop County, Texas!!Households!!Estimate",...,"Wichita County, Texas!!Married-couple families!!Estimate","Wichita County, Texas!!Nonfamily households!!Estimate","Williamson County, Texas!!Households!!Estimate","Williamson County, Texas!!Families!!Estimate","Williamson County, Texas!!Married-couple families!!Estimate","Williamson County, Texas!!Nonfamily households!!Estimate","Wise County, Texas!!Households!!Estimate","Wise County, Texas!!Families!!Estimate","Wise County, Texas!!Married-couple families!!Estimate","Wise County, Texas!!Nonfamily households!!Estimate"
0,Total,"11,087,708","7,483,376","5,401,546","3,604,332","34,276","23,708",N,"10,568","37,278",...,"20,176","19,024","258,095","179,153","144,784","78,942","25,430","18,826",N,"6,604"
1,"Less than $10,000",5.5%,4.0%,1.7%,10.4%,5.1%,2.7%,N,12.0%,6.3%,...,1.5%,7.5%,3.0%,2.1%,1.0%,5.4%,3.0%,1.7%,N,7.0%
2,"$10,000 to $14,999",3.6%,2.1%,1.1%,7.1%,3.9%,2.2%,N,9.6%,3.6%,...,1.1%,9.9%,1.5%,1.0%,0.7%,3.0%,2.4%,0.6%,N,7.7%
3,"$15,000 to $24,999",6.6%,4.8%,2.9%,10.9%,10.5%,5.4%,N,22.5%,6.1%,...,1.6%,17.9%,3.2%,2.2%,1.4%,6.0%,5.2%,3.9%,N,8.6%
4,"$25,000 to $34,999",7.8%,6.6%,4.6%,10.9%,9.5%,4.8%,N,20.0%,5.3%,...,3.0%,14.7%,3.8%,2.8%,2.0%,6.9%,7.3%,5.8%,N,13.1%

In [3]:
# Remove columns we don't care about for the overall project
census_data = census_data[census_data.columns.drop(list(census_data.filter(regex='Families')))]
census_data = census_data[census_data.columns.drop(list(census_data.filter(regex='families')))]
census_data = census_data[census_data.columns.drop(list(census_data.filter(regex='Nonfamily')))]
del census_data['Texas!!Households!!Estimate']

# Flip the table
census_data = census_data.transpose()

# Remove new columns we don't care about for the overall project (PERCENT ALLOCATED)
del census_data[13]

# Turn Row 1 values into Column Headers & delete Row 1 containing prev. Column Headers
census_data.rename(columns=census_data.iloc[0], inplace = True)
census_data.drop(census_data.index[0], inplace=True)

# Check work
census_data.head()

,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months
"Angelina County, Texas!!Households!!Estimate","34,276",5.1%,3.9%,10.5%,9.5%,15.6%,18.0%,11.3%,12.9%,8.4%,4.7%,"58,180","79,881",39.7%,(X),(X)
"Bastrop County, Texas!!Households!!Estimate","37,278",6.3%,3.6%,6.1%,5.3%,12.6%,19.1%,11.8%,21.5%,8.9%,4.9%,"72,663","87,467",41.1%,(X),(X)
"Bell County, Texas!!Households!!Estimate","143,361",6.7%,3.6%,6.9%,8.5%,14.1%,20.2%,13.7%,14.7%,5.5%,6.1%,"62,137","85,250",35.1%,(X),(X)
"Bexar County, Texas!!Households!!Estimate","754,632",5.3%,4.4%,7.9%,8.0%,11.9%,18.6%,13.7%,14.9%,7.9%,7.4%,"65,854","89,010",33.2%,(X),(X)
"Bowie County, Texas!!Households!!Estimate","35,469",8.7%,5.9%,10.3%,9.9%,15.3%,20.3%,9.3%,9.8%,4.6%,5.8%,"49,771","74,515",42.2%,(X),(X)

In [4]:
# Remove 'County, Texas!!Households!!Estimate' from all County names in index
filtered_index = census_data.index.str.split(' ').str[0]
filtered_census_data = census_data.set_index(filtered_index)

# Convert index into Column & reset
filtered_census_data['County'] = filtered_census_data.index
filtered_census_data = filtered_census_data.reset_index()

# Rename columns for ease of later merging & clarity
filtered_census_data = filtered_census_data.rename(columns={'index':'County'})
filtered_census_data = filtered_census_data.rename(columns={'Total':'Total Number of Households'})

# Check work
filtered_census_data.head()

,County,Total Number of Households,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months,County
0,Angelina,"34,276",5.1%,3.9%,10.5%,9.5%,15.6%,18.0%,11.3%,12.9%,8.4%,4.7%,"58,180","79,881",39.7%,(X),(X),Angelina
1,Bastrop,"37,278",6.3%,3.6%,6.1%,5.3%,12.6%,19.1%,11.8%,21.5%,8.9%,4.9%,"72,663","87,467",41.1%,(X),(X),Bastrop
2,Bell,"143,361",6.7%,3.6%,6.9%,8.5%,14.1%,20.2%,13.7%,14.7%,5.5%,6.1%,"62,137","85,250",35.1%,(X),(X),Bell
3,Bexar,"754,632",5.3%,4.4%,7.9%,8.0%,11.9%,18.6%,13.7%,14.9%,7.9%,7.4%,"65,854","89,010",33.2%,(X),(X),Bexar
4,Bowie,"35,469",8.7%,5.9%,10.3%,9.9%,15.3%,20.3%,9.3%,9.8%,4.6%,5.8%,"49,771","74,515",42.2%,(X),(X),Bowie

In [5]:
# Export clean census data to CSV file
filtered_census_data.to_csv('Resources/clean_census_data.csv')

# Child Welfare Data

In [6]:
# Check work
cw_data.head()

   Fiscal Year     County     Region      Type of Allegation  Allegation Count
0         2022  Armstrong  1-Lubbock  Neglectful Supervision                11
1         2022  Armstrong  1-Lubbock          Physical Abuse                 5
2         2022  Armstrong  1-Lubbock            Sexual Abuse                 1
3         2022     Bailey  1-Lubbock         Emotional Abuse                 1
4         2022     Bailey  1-Lubbock  Neglectful Supervision                50

In [7]:
# Convert Allegation Types into Columns via Pivot
pivoted_df = cw_data.pivot_table(index="County", columns="Type of Allegation", 
                                 values="Allegation Count", aggfunc='first')

# Merge Pivot w/ newly-created Columns with pre-existing full child welfare dataset
combined_cw = pd.merge(pivoted_df, cw_data, how = "right", on=["County", "County"])

# Check work
combined_cw.head()

,County,Abandonment,Emotional Abuse,Labor Trafficking,Medical Neglect,Neglectful Supervision,Physical Abuse,Physical Neglect,Refusal To Accept Parental Responsibility,Sex Trafficking,Sexual Abuse,Fiscal Year,Region,Type of Allegation,Allegation Count
0,Armstrong,NaN,1.0,NaN,1.0,11.0,5.0,1.0,NaN,NaN,1.0,2022,1-Lubbock,Neglectful Supervision,11
1,Armstrong,NaN,1.0,NaN,1.0,11.0,5.0,1.0,NaN,NaN,1.0,2022,1-Lubbock,Physical Abuse,5
2,Armstrong,NaN,1.0,NaN,1.0,11.0,5.0,1.0,NaN,NaN,1.0,2022,1-Lubbock,Sexual Abuse,1
3,Bailey,NaN,1.0,NaN,2.0,50.0,19.0,9.0,1.0,NaN,15.0,2022,1-Lubbock,Emotional Abuse,1
4,Bailey,NaN,1.0,NaN,2.0,50.0,19.0,9.0,1.0,NaN,15.0,2022,1-Lubbock,Neglectful Supervision,50

In [8]:
# Drop duplicate rows ==> 1 per County
combined_cw = combined_cw.drop_duplicates(subset = "County", ignore_index = True)

# Turn NaN Cases into 0 Cases
combined_cw = combined_cw.fillna(0) 

# Check work
combined_cw.head()

,County,Abandonment,Emotional Abuse,Labor Trafficking,Medical Neglect,Neglectful Supervision,Physical Abuse,Physical Neglect,Refusal To Accept Parental Responsibility,Sex Trafficking,Sexual Abuse,Fiscal Year,Region,Type of Allegation,Allegation Count
0,Armstrong,0.0,1.0,0.0,1.0,11.0,5.0,1.0,0.0,0.0,1.0,2022,1-Lubbock,Neglectful Supervision,11
1,Bailey,0.0,1.0,0.0,2.0,50.0,19.0,9.0,1.0,0.0,15.0,2022,1-Lubbock,Emotional Abuse,1
2,Briscoe,0.0,2.0,0.0,1.0,8.0,2.0,1.0,1.0,0.0,1.0,2022,1-Lubbock,Neglectful Supervision,8
3,Carson,2.0,1.0,0.0,4.0,31.0,12.0,3.0,1.0,1.0,12.0,2022,1-Lubbock,Emotional Abuse,1
4,Castro,0.0,5.0,1.0,8.0,45.0,19.0,6.0,0.0,1.0,13.0,2022,1-Lubbock,Emotional Abuse,5

In [9]:
# Export clean child welfare data to CSV file
combined_cw.to_csv('Resources/clean_cw_data.csv')

# Merging Datasets

In [10]:
filtered_census_data.head()

,County,Total Number of Households,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months,County
0,Angelina,"34,276",5.1%,3.9%,10.5%,9.5%,15.6%,18.0%,11.3%,12.9%,8.4%,4.7%,"58,180","79,881",39.7%,(X),(X),Angelina
1,Bastrop,"37,278",6.3%,3.6%,6.1%,5.3%,12.6%,19.1%,11.8%,21.5%,8.9%,4.9%,"72,663","87,467",41.1%,(X),(X),Bastrop
2,Bell,"143,361",6.7%,3.6%,6.9%,8.5%,14.1%,20.2%,13.7%,14.7%,5.5%,6.1%,"62,137","85,250",35.1%,(X),(X),Bell
3,Bexar,"754,632",5.3%,4.4%,7.9%,8.0%,11.9%,18.6%,13.7%,14.9%,7.9%,7.4%,"65,854","89,010",33.2%,(X),(X),Bexar
4,Bowie,"35,469",8.7%,5.9%,10.3%,9.9%,15.3%,20.3%,9.3%,9.8%,4.6%,5.8%,"49,771","74,515",42.2%,(X),(X),Bowie

In [12]:
# Merge Census & Child Welfare data
happy_childhood_data = pd.merge(filtered_census_data, combined_cw, on=["County","County"])

# Drop rows w/ NaN values
happy_childhood_data = happy_childhood_data.dropna()

# Check Work
happy_childhood_data.head()

ValueError: The column label 'County' is not unique.

In [ ]:
# Export full clean dataset to CSV file for later analysis for overall project
happy_childhood_data.to_csv('Resources/full_clean_dataset.csv')