In [17]:
# Import dependencies
import pandas as pd
from pathlib import Path 
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

# Establish data path & read in CSV
data_path = "Resources/full_clean_dataset.csv"
df = pd.read_csv(data_path) 

# df = df.rename(columns={'Total':'Total Number of Households'})
# df = df.drop(columns="Unnamed: 0")
df = df.dropna()

# Create new df with vaues needed to answer question, "Does household income affect type of cases?"
income_type_df = df[['Region','County', 'Total Number of Households', 'Median income (dollars)', 'Abandonment', 'Emotional Abuse',
                     'Medical Neglect', 'Neglectful Supervision', 'Physical Abuse', 'Physical Neglect',
                     'Refusal To Accept Parental Responsibility', 'Sex Trafficking', 'Sexual Abuse']]
# Check work
income_type_df.head()

,Region,County,Total Number of Households,Median income (dollars),Abandonment,Emotional Abuse,Medical Neglect,Neglectful Supervision,Physical Abuse,Physical Neglect,Refusal To Accept Parental Responsibility,Sex Trafficking,Sexual Abuse
0,5-Beaumont,Angelina,"34,276","58,180",3.0,32.0,63.0,684.0,226.0,113.0,5.0,2.0,255.0
1,7-Austin,Bastrop,"37,278","72,663",1.0,45.0,46.0,690.0,254.0,77.0,8.0,3.0,250.0
2,7-Austin,Bell,"143,361","62,137",24.0,154.0,292.0,3655.0,1219.0,455.0,67.0,12.0,852.0
3,8-San Antonio,Bexar,"754,632","65,854",43.0,832.0,1224.0,15509.0,5221.0,1766.0,186.0,59.0,4594.0
4,4-Tyler,Bowie,"35,469","49,771",5.0,34.0,63.0,722.0,248.0,167.0,10.0,3.0,240.0

In [18]:
# plt.scatter(df["Abandonment"], df["Median income (dollars)"])
# plt.show()

# Remove commas from numbers (Ex. 5,000 ==> 5000)
income_type_df["Median income (dollars)"] = income_type_df["Median income (dollars)"].replace(",", "", regex = True)
income_type_df["Total Number of Households"] = income_type_df["Total Number of Households"].replace(",", "", regex = True)
# print(df["Median income (dollars)"] )

# Convert from string to float datatype
income_type_df = income_type_df.astype({"Median income (dollars)" : 'float'})
income_type_df = income_type_df.astype({"Total Number of Households" : 'float'})

#Check work
income_type_df.dtypes

C:\Users\mojo\AppData\Local\Temp\ipykernel_17396\81490173.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  income_type_df["Median income (dollars)"] = income_type_df["Median income (dollars)"].replace(",", "", regex = True)
C:\Users\mojo\AppData\Local\Temp\ipykernel_17396\81490173.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  income_type_df["Total Number of Households"] = income_type_df["Total Number of Households"].replace(",", "", regex = True)

Region                                        object
County                                        object
Total Number of Households                   float64
Median income (dollars)                      float64
Abandonment                                  float64
Emotional Abuse                              float64
Medical Neglect                              float64
Neglectful Supervision                       float64
Physical Abuse                               float64
Physical Neglect                             float64
Refusal To Accept Parental Responsibility    float64
Sex Trafficking                              float64
Sexual Abuse                                 float64
dtype: object

In [66]:
# Find correlation coefficient
allegation_type = income_type_df["Abandonment"]
income = income_type_df["Median income (dollars)"]
correlation = st.pearsonr(income, allegation_type)

# The next example will compute the Pearson correlation coefficient between "Income per Capita" and "Average Alcohol Consumed"
# income = wdi_data.iloc[:,1]
# alcohol = wdi_data.iloc[:,8]
# correlation = st.pearsonr(income,alcohol)
# print(f"The correlation between both factors is {round(correlation[0],2)}")
print(f"The correlation with Abandonment is: {round(correlation[0],2)}")

allegation_type = income_type_df["Emotional Abuse"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Emotional Abuse is: {round(correlation[0],2)}")

allegation_type = income_type_df["Medical Neglect"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Medical Neglect is: {round(correlation[0],2)}")

allegation_type = income_type_df["Neglectful Supervision"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Neglectful Supervision is: {round(correlation[0],2)}")

allegation_type = income_type_df["Physical Abuse"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Physical Abuse is: {round(correlation[0],2)}")

allegation_type = income_type_df["Physical Abuse"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Physical Abuse is: {round(correlation[0],2)}")

allegation_type = income_type_df["Physical Neglect"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Physical Neglect is: {round(correlation[0],2)}")

allegation_type = income_type_df["Refusal To Accept Parental Responsibility"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Refusal To Accept Parental Responsibility  is: {round(correlation[0],2)}")

allegation_type = income_type_df["Sex Trafficking"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Sex Trafficking is: {round(correlation[0],2)}")

allegation_type = income_type_df["Sexual Abuse"]
correlation = st.pearsonr(income, allegation_type)
print(f"The correlation with Sexual Abuse is: {round(correlation[0],2)}")

The correlation with Abandonment is: 0.0
The correlation with Emotional Abuse is: 0.07
The correlation with Medical Neglect is: 0.03
The correlation with Neglectful Supervision is: 0.01
The correlation with Physical Abuse is: 0.02
The correlation with Physical Abuse is: 0.02
The correlation with Physical Neglect is: -0.04
The correlation with Refusal To Accept Parental Responsibility  is: 0.0
The correlation with Sex Trafficking is: 0.02
The correlation with Sexual Abuse is: 0.0

In [68]:
for x in income_type_df.columns[5:]:
    # get individual column header
    allegation_name = income_type_df[x].head()
    
    # get individual column contents
    allegation_type = income_type_df[x]
    
    # get & show correlation
    correlation = st.pearsonr(income, allegation_type)
    print(f"The correlation with {allegation_name} is: {round(correlation[0],2)}")
    
    # iterate counter
    x = x+1

The correlation with 0     32.0
1     45.0
2    154.0
3    832.0
4     34.0
Name: Emotional Abuse, dtype: float64 is: 0.07

TypeError: can only concatenate str (not "int") to str